

version: '3'


services:

  wikidb:
    image: mongo:3
    ports:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    networks:
      - wikinet
    volumes:
      - db-data:/data/db


  wikijs:
    image: 'requarks/wiki:latest'
    depends_on:
      - wikidb
    ports:
      - '3000:3000'
    environment:
      WIKI_ADMIN_EMAIL: andrea.rigoni@igi.cnr.it
    networks:
      - wikinet      
    volumes:
      - ${abs_srcdir}/config_v1.yml:/var/wiki/config.yml
    entrypoint: /bin/bash
    tty: true
    stdin_open: true




networks:
  wikinet:

volumes:
  db-data: